# Generated by Django 5.0.6 on 2024-06-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contrasenya', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=200)),
                ('correu', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('codi_lot', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('nom_tmp', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('username_agricultor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='econet.usuari')),
                ('descripcio', models.CharField(max_length=255)),
                ('codi_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('username_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='econet.usuari')),
                ('direccio_denviament', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codi_cat', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_cat', models.CharField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='econet.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_pro', models.CharField(max_length=100, unique=True)),
                ('nom_pro', models.CharField(max_length=255)),
                ('descripcio', models.TextField(max_length=255)),
                ('preu', models.FloatField()),
                ('unitari', models.BooleanField()),
                ('data_limit', models.DateTimeField()),
                ('quantitat_disponible', models.IntegerField()),
                ('descompte', models.FloatField()),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.agricultor')),
            ],
            options={
                'unique_together': {('agricultor', 'codi_pro')},
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_compra', models.DateTimeField(unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.client')),
            ],
            options={
                'unique_together': {('client', 'data_de_compra')},
            },
        ),
        migrations.CreateModel(
            name='Pertany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.categoria')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.producte')),
            ],
            options={
                'unique_together': {('producte', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.lot')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.producte')),
            ],
            options={
                'unique_together': {('producte', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='Element_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.FloatField()),
                ('preu_pagat', models.FloatField()),
                ('es_lot', models.BooleanField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.compra')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.producte')),
            ],
            options={
                'unique_together': {('producte', 'compra')},
            },
        ),
        migrations.CreateModel(
            name='Es',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.producte')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='econet.temporada')),
            ],
            options={
                'unique_together': {('producte', 'temporada')},
            },
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField()),
                ('data_valoracio', models.DateTimeField()),
                ('descripcio', models.TextField(max_length=255)),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.producte')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='econet.client')),
            ],
            options={
                'unique_together': {('producte', 'client')},
            },
        ),
    ]
