# Generated by Django 5.0.6 on 2024-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contrasenya', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=200)),
                ('correu', models.EmailField(max_length=255)),
            ],
        ),
    ]
